train:
  epochs: 1
  batch_size: 2
  lr: 2.0e-4
  seq_len: 512
model:
  n_layer: 2
  n_head: 2
  n_embd: 128
  vocab_path: data/processed/vocab.json
data:
  train_jsonl: data/processed/jsonl/train.jsonl
