name: Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: ${{ github.workspace }}
      # 테스트는 오디오/OV 없이도 통과(안정성 목적)
      ALLOW_FAKE_GEN: "1"
      SKIP_AUDIO: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Mypy (type check)
        run: mypy src || true

      - name: Pytest (unit)
        run: pytest -q
